version: '3'
services:
  server:
    image: node:12-alpine
    container_name: todo-server
    working_dir: /develop
    volumes:
      # 最低限のディレクトリのみ連携する
      - ./packages/server/package.json:/develop/package.json
      - ./packages/server/node_modules:/develop/node_modules
      - ./packages/server/dist:/develop/dist
      # フロント側のビルドディレクトリは名前がかぶるため、リネームして配置
      - ./packages/front/dist:/develop/public
    links:
      - db
    command: 'npm run start:prod'
    environment:
      - PORT=${SERVER_PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  db:
    image: postgres:12-alpine
    container_name: todo-db
    ports:
      - 5432:5432
    volumes:
      - .db/prod/data:/var/lib/postgresql/data
      - .db/prod/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}

  proxy:
    image: nginx
    container_name: todo-proxy
    depends_on:
      - server
    volumes:
      - ./nginx/prod.conf.template:/etc/nginx/templates/default.conf.template
      # - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - SERVER_PORT=${SERVER_PORT}
