version: "3"
services:
  server-dev:
    image: node:12-alpine
    container_name: server-dev
    working_dir: /develop
    volumes:
      - ./packages/server:/develop
    ports:
      - 3000:3000
    links:
      - todo-db-dev
    command: "npm run start:dev"
    environment:
      - PORT=${SERVER_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  front:
    image: node:12-alpine
    container_name: front
    working_dir: /develop
    volumes:
      - ./packages/front:/develop
    ports:
      - 80:3000
    command: "npm run dev"
    environment:
      - API_BASE_URL=${SERVER_HOST}:${SERVER_PORT}

  todo-db-dev:
    image: postgres:12-alpine
    container_name: todo-db-dev
    ports:
      - 5432:5432
    volumes:
      - .db/dev/data:/var/lib/postgresql/data
      - .db/dev/initdb:/docker-entrypoint-initdb.d
    environment:
      - API_BASE_URL=
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}

  db-client:
    image: adminer
    container_name: db-client
    links:
      - todo-db-dev
    ports:
      - 8080:8080
