version: '3'
services:
  server:
    image: node:12-alpine
    container_name: todo-server-dev
    working_dir: /develop
    volumes:
      - ./packages/server:/develop
    depends_on:
      - db
    command: 'npm run start:dev'
    environment:
      - PORT=${SERVER_PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  front:
    image: node:12-alpine
    container_name: todo-front-dev
    working_dir: /develop
    volumes:
      - ./packages/front:/develop
    command: 'npm run dev'
    environment:
      - PORT=${FRONT_PORT}

  db:
    image: postgres:12-alpine
    container_name: todo-db-dev
    ports:
      - 5432:5432
    volumes:
      - .db/dev/data:/var/lib/postgresql/data
      - .db/dev/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}

  db-client:
    image: adminer
    container_name: db-client
    links:
      - db
    ports:
      - 8080:8080

  # フロントもNuxtサーバーでコンテナを立てているため、リバプロサーバーを立てて
  # localhostでフロント／サーバー両方にアクセスできるようにする
  proxy:
    image: nginx
    container_name: todo-proxy
    depends_on:
      - server
      - front
    volumes:
      - ./nginx/dev.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - FRONT_PORT=${FRONT_PORT}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8000:80
    volumes:
      - ./.db/pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
